"""initial schema

Revision ID: a44f0b8d830b
Revises: 
Create Date: 2026-09-10 19:31:40.637326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44f0b8d830b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chemistry_version', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('camera_profile', sa.String(), nullable=True),
    sa.Column('concentration_range_min_ppm', sa.Float(), nullable=True),
    sa.Column('concentration_range_max_ppm', sa.Float(), nullable=True),
    sa.Column('curve_points', sa.JSON(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_threshold_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ppm_elevated', sa.Float(), nullable=False),
    sa.Column('ppm_high', sa.Float(), nullable=False),
    sa.Column('ppm_critical', sa.Float(), nullable=False),
    sa.Column('dose_elevated_ppm_min', sa.Float(), nullable=False),
    sa.Column('dose_high_ppm_min', sa.Float(), nullable=False),
    sa.Column('dose_critical_ppm_min', sa.Float(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'SUPERVISOR', 'MANAGER', 'SAFETY_ADMIN', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strip_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('manufactured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['calibration_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('site_threshold_profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_threshold_profile_id'], ['site_threshold_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.create_table('strips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strip_code', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRING_SOON', 'EXPIRED', 'INVALID', name='stripstatus'), nullable=True),
    sa.Column('health_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['strip_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strips_strip_code'), 'strips', ['strip_code'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('supervisor_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('shift_label', sa.String(), nullable=True),
    sa.Column('active_strip_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['active_strip_id'], ['strips.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_scan_uuid', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('strip_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('calibration_profile_id', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('optical_response', sa.Float(), nullable=True),
    sa.Column('estimated_ppm', sa.Float(), nullable=True),
    sa.Column('dose_ppm_min', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_ok', sa.Boolean(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'ELEVATED', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('risk_explanation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'SYNC_FAILED', name='syncstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_profile_id'], ['calibration_profiles.id'], ),
    sa.ForeignKeyConstraint(['strip_id'], ['strips.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_client_scan_uuid'), 'scans', ['client_scan_uuid'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LOW', 'ELEVATED', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exposure_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('dose_ppm_min', sa.Float(), nullable=True),
    sa.Column('cumulative_dose_ppm_min', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'ELEVATED', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exposure_events')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_scans_client_scan_uuid'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('workers')
    op.drop_index(op.f('ix_strips_strip_code'), table_name='strips')
    op.drop_table('strips')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('strip_batches')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('site_threshold_profiles')
    op.drop_table('calibration_profiles')
    # ### end Alembic commands ###
